run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  
  disable:
    - errcheck
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: internal/web/webapp_static.go
      linters:
        - typecheck

