-- Localize seeded Spanish word set categories/sets/descriptions from EN to ES in-place.
-- Safe/idempotent: updates only known EN labels generated by 000002 migration.

-- Categories
UPDATE word_set_categories
SET
  name = 'Frecuencia esencial',
  description = 'Vocabulario de alta frecuencia para conversaciones y textos cotidianos.'
WHERE parent_id IS NULL AND name = 'Core Frequency';

UPDATE word_set_categories
SET
  name = 'Frecuencia ampliada',
  description = 'Palabras de frecuencia media para ampliar el vocabulario diario.'
WHERE parent_id IS NULL AND name = 'Extended Frequency';

UPDATE word_set_categories
SET
  name = 'Top 500 verbos',
  description = 'Verbos de alta frecuencia usados en el habla y en textos cotidianos.'
WHERE name = 'Top 500 Verbs';

UPDATE word_set_categories
SET
  name = 'Top 500 sustantivos',
  description = 'Sustantivos de alta frecuencia usados en conversaciones y textos cotidianos.'
WHERE name = 'Top 500 Nouns';

UPDATE word_set_categories
SET
  name = 'Top 500 adjetivos',
  description = 'Adjetivos de alta frecuencia para describir personas, cosas y situaciones.'
WHERE name = 'Top 500 Adjectives';

UPDATE word_set_categories
SET
  name = 'Top adverbios',
  description = 'Adverbios de alta frecuencia para tiempo, frecuencia, grado y modo.'
WHERE name = 'Top Adverbs';

UPDATE word_set_categories
SET
  name = 'Top 500-1000 sustantivos',
  description = 'Sustantivos de frecuencia media (rango 501-1000) para ampliar el vocabulario base.'
WHERE name = 'Top 500–1000 Nouns';

UPDATE word_set_categories
SET
  name = 'Top 1001-1500 sustantivos',
  description = 'Sustantivos de frecuencia ampliada (rangos 1001-1500 dentro de sustantivos).'
WHERE name = 'Top 1001–1500 Nouns';

UPDATE word_set_categories
SET
  name = 'Top 1501-2000 sustantivos',
  description = 'Sustantivos de frecuencia ampliada (rangos 1501-2000 dentro de sustantivos).'
WHERE name = 'Top 1501–2000 Nouns';

-- Sets: Core Verbs
UPDATE word_sets
SET
  title = 'Verbos esenciales — Top 50 (rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ')',
  description = 'Verbos en los rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ' por frecuencia (dentro de verbos).'
WHERE title LIKE 'Core Verbs — Top 50 (Ranks %)';

-- Sets: Core Nouns (both 1-500 and 501-1000 blocks)
UPDATE word_sets
SET
  title = 'Sustantivos esenciales — Top 50 (rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ')',
  description = 'Sustantivos en los rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ' por frecuencia (dentro de sustantivos).'
WHERE title LIKE 'Core Nouns — Top 50 (Ranks %)';

-- Sets: Core Adjectives
UPDATE word_sets
SET
  title = 'Adjetivos esenciales — Top 50 (rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ')',
  description = 'Adjetivos en los rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ' por frecuencia (dentro de adjetivos).'
WHERE title LIKE 'Core Adjectives — Top 50 (Ranks %)';

-- Sets: Core Adverbs
UPDATE word_sets
SET
  title = 'Adverbios esenciales — Top 50 (rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ')',
  description = 'Adverbios en los rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ' por frecuencia (dentro de adverbios).'
WHERE title LIKE 'Core Adverbs — Top 50 (Ranks %)';

-- Sets: Extended Nouns
UPDATE word_sets
SET
  title = 'Sustantivos ampliados — Top 50 (rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ')',
  description = 'Sustantivos en los rangos ' || substring(title from 'Ranks ([0-9–-]+)') || ' por frecuencia (dentro de sustantivos).'
WHERE title LIKE 'Extended Nouns — Top 50 (Ranks %)';
