package spanishverbs

import "strings"

// defaultLemmaRuGloss is a small offline map (RU literary gloss / main sense) for common lemmas before DB/LLM fill.
// Extend via `make backfill-verb-lemma-ru-glosses` or metadata in verb_lemmas.
var defaultLemmaRuGloss = map[string]string{
	"abandonar":  "бросать, оставлять",
	"aceptar":    "принимать, соглашаться",
	"andar":      "идти, ходить",
	"bajar":      "спускаться, снижать",
	"buscar":     "искать",
	"caer":       "падать",
	"cambiar":    "менять",
	"caminar":    "идти пешком",
	"comenzar":   "начинать",
	"comer":      "есть",
	"comprender": "понимать",
	"conocer":    "знать, быть знакомым",
	"contar":     "считать, рассказывать",
	"correr":     "бежать",
	"crear":      "создавать",
	"creer":      "верить, думать",
	"cruzar":     "пересекать",
	"dar":        "давать",
	"decir":      "говорить",
	"deber":      "должный, быть должным",
	"dejar":      "оставлять, позволять",
	"descansar":  "отдыхать",
	"desear":     "желать",
	"entender":   "понимать",
	"entrar":     "входить",
	"escribir":   "писать",
	"escuchar":   "слушать",
	"esperar":    "ждать, надеяться",
	"estar":      "быть (состояние/место)",
	"explicar":   "объяснять",
	"ganar":      "выигрывать, зарабатывать",
	"gustar":     "нравиться",
	"haber":      "иметь",
	"hablar":     "говорить",
	"hacer":      "делать",
	"ir":         "идти",
	"levantar":   "поднимать",
	"llamar":     "звать, называть",
	"llegar":     "приходить, прибывать",
	"llevar":     "нести, вести",
	"mirar":      "смотреть",
	"necesitar":  "нуждаться",
	"olvidar":    "забывать",
	"pasar":      "проходить, случаться",
	"pensar":     "думать",
	"perder":     "терять",
	"poder":      "мочь",
	"poner":      "класть, ставить",
	"preguntar":  "спрашивать",
	"querer":     "хотеть, любить",
	"recibir":    "получать",
	"recordar":   "помнить, напоминать",
	"resultar":   "оказываться",
	"saber":      "знать, уметь",
	"salir":      "выходить",
	"seguir":     "следовать, продолжать",
	"sentir":     "чувствовать",
	"ser":        "быть",
	"servir":     "служить",
	"subir":      "подниматься",
	"suponer":    "предполагать",
	"temer":      "бояться",
	"tomar":      "брать",
	"trabajar":   "работать",
	"traer":      "приносить",
	"tratar":     "пытаться, обращаться",
	"usar":       "использовать",
	"venir":      "приходить",
	"ver":        "видеть",
	"vender":     "продавать",
	"vivir":      "жить",
	"volver":     "возвращаться",

	// Top-frequency pack (Freq100VerbLemmas) — краткие глоссы для cloze без БД/LLM.
	"encontrar":    "находить, встречать",
	"quedar":       "оставаться, оказываться",
	"mantener":     "держать, поддерживать",
	"presentar":    "представлять",
	"considerar":   "считать, рассматривать",
	"realizar":     "выполнять, осуществлять",
	"asegurar":     "уверять, обеспечивать",
	"permitir":     "позволять",
	"jugar":        "играть",
	"pedir":        "просить",
	"conseguir":    "добиваться, получать",
	"producir":     "производить",
	"convertir":    "превращать",
	"lograr":       "удаваться, достигать",
	"incluir":      "включать",
	"parecer":      "казаться",
	"decidir":      "решать",
	"afirmar":      "утверждать",
	"mostrar":      "показывать",
	"utilizar":     "использовать",
	"existir":      "существовать",
	"señalar":      "указывать",
	"destacar":     "выделять",
	"anunciar":     "объявлять",
	"formar":       "формировать",
	"partir":       "отправляться, делить",
	"intentar":     "пытаться",
	"participar":   "участвовать",
	"situar":       "располагать",
	"añadir":       "добавлять",
	"alcanzar":     "достигать",
	"ofrecer":      "предлагать",
	"acabar":       "заканчивать",
	"ubicar":       "располагать",
	"nacer":        "рождаться",
	"reconocer":    "признавать",
	"indicar":      "указывать",
	"empezar":      "начинать",
	"informar":     "информировать",
	"aparecer":     "появляться",
	"obtener":      "получать",
	"dirigir":      "направлять",
	"celebrar":     "отмечать, праздновать",
	"declarar":     "заявлять",
	"sufrir":       "страдать",
	"evitar":       "избегать",
	"abrir":        "открывать",
	"morir":        "умирать",
	"cumplir":      "выполнять",
	"representar":  "представлять",
	"continuar":    "продолжать",
	"establecer":   "устанавливать",
	"dedicar":      "посвящать",
	"iniciar":      "начинать",
	"tener":        "иметь",
}

// DefaultRuGloss returns embedded Russian gloss for lemma if present (lemma lowercased).
func DefaultRuGloss(lemma string) string {
	if s, ok := defaultLemmaRuGloss[strings.ToLower(strings.TrimSpace(lemma))]; ok {
		return s
	}
	return ""
}
