#!/usr/bin/env python3
"""Regenerate scripts/download-reading-voices.sh from HF rhasspy/piper-voices main branch."""

import json
import urllib.request

BASE = "https://huggingface.co/api/models/rhasspy/piper-voices/tree/main"
QUALITY_RANK = {"high": 0, "medium": 1, "low": 2, "x_low": 3}
ROOT = "https://huggingface.co/rhasspy/piper-voices/resolve/main"


def fetch(path: str):
    return json.loads(urllib.request.urlopen(f"{BASE}/{path}", timeout=120).read().decode())


def scan_lang(lang: str):
    rows = []
    for loc in fetch(lang):
        if loc["type"] != "directory":
            continue
        lp = loc["path"]
        for v in fetch(lp):
            if v["type"] != "directory":
                continue
            vp = v["path"]
            for t in fetch(vp):
                if t["type"] != "directory":
                    continue
                tp = t["path"]
                tier = tp.split("/")[-1]
                if tier not in QUALITY_RANK:
                    continue
                for f in fetch(tp):
                    if f["type"] != "file" or not f["path"].endswith(".onnx"):
                        continue
                    if "samples" in f["path"]:
                        continue
                    rows.append((QUALITY_RANK[tier], tier, f["path"]))
    rows.sort(key=lambda x: (x[0], x[2]))
    return rows


def main():
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        'VOICE_DIR="${1:-${HOME}/tts/voices}"',
        'mkdir -p "$VOICE_DIR"',
        "",
        "download_voice() {",
        '  local voice_id="$1"',
        '  local onnx_url="$2"',
        '  local json_url="$3"',
        '  echo "Downloading ${voice_id}..."',
        '  curl -fL "$onnx_url" -o "${VOICE_DIR}/${voice_id}.onnx"',
        '  curl -fL "$json_url" -o "${VOICE_DIR}/${voice_id}.onnx.json"',
        "}",
        "",
        "# Auto-generated by scripts/regenerate-reading-voice-downloads.py — edit generator, not URLs by hand.",
        "# Narrators: best neutral reading voices (EN lessac high; ES sharvard medium — only neutral ES in catalog).",
        "download_voice \\",
        '  "en_narrator" \\',
        f'  "{ROOT}/en/en_US/lessac/high/en_US-lessac-high.onnx" \\',
        f'  "{ROOT}/en/en_US/lessac/high/en_US-lessac-high.onnx.json"',
        "",
        "download_voice \\",
        '  "es_narrator" \\',
        f'  "{ROOT}/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx" \\',
        f'  "{ROOT}/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx.json"',
        "",
        "# --- Spanish: full set on HF main (quality high → x_low) ---",
    ]
    for _, _tier, path in scan_lang("es"):
        bn = path.split("/")[-1].replace(".onnx", "")
        vid = bn.replace("-", "_")
        lines.extend(
            [
                "download_voice \\",
                f'  "{vid}" \\',
                f'  "{ROOT}/{path}" \\',
                f'  "{ROOT}/{path}.json"',
                "",
            ]
        )
    lines.append("# --- English: full set on HF main (quality high → low) ---")
    for _, _tier, path in scan_lang("en"):
        bn = path.split("/")[-1].replace(".onnx", "")
        vid = bn.replace("-", "_")
        extra = []
        if bn == "en_US-lessac-high":
            extra = ["# Canonical lessac-high id (duplicate file of en_narrator; same bytes)."]
        lines.extend(extra)
        lines.extend(
            [
                "download_voice \\",
                f'  "{vid}" \\',
                f'  "{ROOT}/{path}" \\',
                f'  "{ROOT}/{path}.json"',
                "",
            ]
        )
    lines.append('echo "Done. Voices saved to: ${VOICE_DIR}"')

    out_path = __file__.replace("regenerate-reading-voice-downloads.py", "").rstrip("/") + "/download-reading-voices.sh"
    # __file__ is scripts/regenerate-reading-voice-downloads.py
    import os

    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "download-reading-voices.sh")
    text = "\n".join(lines) + "\n"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(out_path, 0o755)
    print(f"Wrote {out_path} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
