plugins {
    id "com.android.application"
}

android {
    namespace "ru.qantrix.embedded"
    compileSdk 35

    defaultConfig {
        minSdk 23
        targetSdk 35
        versionCode Integer.parseInt(System.getenv("ANDROID_VERSION_CODE") ?: "1")
        versionName System.getenv("ANDROID_VERSION_NAME") ?: "0.0.0"
    }

    buildFeatures {
        buildConfig true
    }

    sourceSets {
        main.assets.srcDirs = ["src/main/assets"]
    }

    flavorDimensions "language"
    productFlavors {
        english {
            dimension "language"
            applicationId "ru.qantrix.english"
            resValue "string", "app_name", "Qantrix English"
            buildConfigField "String", "APP_HOST", "\"qantrix.ru\""
            buildConfigField "String", "START_URL", "\"https://qantrix.ru/app/\""
        }
        spanish {
            dimension "language"
            applicationId "ru.qantrix.spanish"
            resValue "string", "app_name", "Qantrix Spanish"
            buildConfigField "String", "APP_HOST", "\"es.qantrix.ru\""
            buildConfigField "String", "START_URL", "\"https://es.qantrix.ru/app/\""
        }
    }
}

dependencies {
}
